[build]
  command = "npm run build"
  publish = ".next"

# Plugin esensial untuk Next.js 15 di Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_LOCAL_WEBPACK = "true"